ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\fastapi\routing.py", line 328, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tohid\OneDrive\Desktop\ocr\env\Lib\site-packages\fastapi\routing.py", line 177, in serialize_response
    raise ResponseValidationError(
fastapi.exceptions.ResponseValidationError: 8 validation errors:
  {'type': 'missing', 'loc': ('response', 'extracted_data', 0, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'dli', 'amount': 132.0, 'category': 'Food', 'mode': 'other'}}
  {'type': 'missing', 'loc': ('response', 'extracted_data', 1, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'Ghee Podi Idli', 'amount': 88.0, 'category': 'Food', 'mode': 'other'}}
  {'type': 'missing', 'loc': ('response', 'extracted_data', 2, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'Masala Dosa', 'amount': 122.1, 'category': 'Food', 'mode': 'other'}}
  {'type': 'missing', 'loc': ('response', 'extracted_data', 3, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'Chettinad Masala Dosa', 'amount': 171.6, 'category': 'Food', 'mode': 'other'}}
  {'type': 'missing', 'loc': ('response', 'extracted_data', 4, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'Mysore Masala Dosa', 'amount': 181.5, 'category': 'Food', 'mode': 'other'}}
  {'type': 'missing', 'loc': ('response', 'extracted_data', 5, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'Packing Charge', 'amount': 69.52, 'category': 'Services', 'mode': 'other'}}
  {'type': 'missing', 'loc': ('response', 'extracted_data', 6, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'CGST', 'amount': 19.17, 'category': 'Taxes', 'mode': 'other'}}
  {'type': 'missing', 'loc': ('response', 'extracted_data', 7, 'product_name'), 'msg': 'Field required', 'input': {'bill_no': '22417', 'expence_name': 'SGST', 'amount': 19.12, 'category': 'Taxes', 'mode': 'other'}}